# Site settings
title: BCN Dev Blog
email: adam@thehoick.com
description: Development Blog for the Boone Community Network and the BCN Rails project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devblog.boonecommunitynetwork.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title/

excerpt_separator: <!--more-->

sass:
  sass_dir: css

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      is_post: true
      author: Adam Sommer
      author_twitter: 'https://twitter.com/asommer'
